DotBlog/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from blog import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', views.homepage, name='homepage'),
    path('blog/<int:id>/', views.writings, name='writings'),
    path('', views.home, name='home'),
    path('aboutus/', views.aboutus, name="aboutus"),
    path('privacy-policy', views.privacy,name="privacy"),
    path('faq',views.faq, name="faq"),
    path('authors/', views.authors, name = 'authors'),
   path('blog/create', views.create_blog, name='create_blog'),
]

urlpatterns = urlpatterns + staticfiles_urlpatterns()

accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

app_name ='accounts'

urlpatterns=[
    path('signup/', views.signup_views, name ='signup'),
    path('login/', views.login_views, name = 'login'),
    path('logout/', views.logout_views, name = 'logout'),
]

accounts/models.py
from django.db import models

blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()


    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from . import models

class CreateBlog(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from . import models
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_views(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/blog/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form':form})


def login_views(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/blog/')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})

def logout_views(request):
    if request.method=='POST':
        logout(request)
        return redirect('/accounts/login/')

blog/views.py
from django.shortcuts import render, redirect
from .models import Article
#from .models import Author
from django.contrib import messages
#from  django.db import Q
from django.contrib.auth.decorators import login_required
from . import forms




def homepage(request):
    articles = Article.objects.all()
    return render(request, 'homepage.html', {'articles':articles})


def writings(request, id):
    material = Article.objects.get(id=id)
    return render(request, 'writings.html', {'material':material})


def home(request):
    return render(request, 'home.html')

def aboutus(request):
    return render(request, 'about_us.html')

def privacy (request):
    return render(request, 'privacy.html')

def faq (request):
    return render(request, 'faq.html')

def authors(request):
    author = Article.objects.all()
    return render(request, 'authors.html', {'author':author})

def author_detail(request, id):
    detail = Article




"""def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = utils.get_query(query_string, ['title', 'author',])
        posts = Post.objects.filter(entry_query).order_by('created')
        return render(request, 'base.html', { 'query_string': query_string, 'posts': posts })
    else:
        return render(request, 'base.html', { 'query_string': 'Null', 'found_entries': 'Enter a search term' })
"""

@login_required(login_url="/accounts/login")
def create_blog(request):
    if request.method =='POST':
        form = forms.CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            #saving the forms
            instance = form.save(commit=False)   #Doesnt save instantly but is refering to a variable
            instance.author = request.user       #selecting the exact same loggedin author for the article
            instance.save()                      #finally saving the article
            return redirect('/blog/')
    else:
        form = forms.CreateBlog()
    return render(request, 'add_article.html', {'form':form})

accounts/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head><link rel="stylesheet" href="{% static 'css/all.css' %}">
    <meta charset="utf-8">
    <title>LOGIN</title>
  </head>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
  <a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>
  <body style="background-image: url('{% static "images/back4.jpg" %}');height:600px;";>
      <style>
          #middle {
            position: relative;
            padding :10Px;
            top :40%;
            left :30%;
          }
          .button {
  display: inline-block;
  border-radius: 2px;
  background-color: #011e25;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 18px;
  padding: 10px;
  width: 100px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 3px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
          </style>
    <div id='middle' style="border-radius:15px ;border:2px solid black; position: absolute; height: 22% width= 20%;"> 
        <form class="site-form" action="/accounts/login/" method="POST">
          {% csrf_token %}
          {{ form.as_p}}
          {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}">
         {% endif %}
         <input type="submit" value ="Login">
        </form>
         <hr>
        <h3>Need a account?<a href="{% url 'accounts:signup' %}"><button class='button'><span>Signup</span> </button></a>
        </h3>
        
      
    </div>
    <div style="border: thin 2px; bottom:-500px; position: relative; ">
        <div align="center" id="footer"> 
            <a href="{% url 'aboutus' %}">About Us</a>
            <a href="{% url 'privacy' %}">Privacy Policy</a>
            
            <a href="{% url 'faq' %}">FAQ</a>
          
        </div>
    <footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
    </div>
  </body>
</html>

accounts/templates/logout.html
<!DOCTYPE html>
<html>
    
</html>

accounts/templates/profile.htm
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{user.profile.image.url}}">
        <div class="media-body">
            <h2 class="account-heading">{{User.name}}</h2>
            <p class="text-secondary">{{user.email}}</p>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/profile.html
{%extends 'base.html'%}
<head>
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
        <link rel="stylesheet" href="{% static 'css/all.css' %}">
</head>
{%block content%}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{user.profile.image.url}}">
        <div class="media-body">
            <h2 class="account-heading">{{User.name}}</h2>
            <p class="text-secondary">{{user.email}}</p>
        </div>
    </div>
    <div align="center" id="footer"> 
            <a href="{% url 'aboutus' %}">About Us</a>
            <a href="{% url 'privacy' %}">Privacy Policy</a>
            
            <a href="{% url 'faq' %}">FAQ</a>
          
        </div>
    <footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
</div>
{% endblock content %}

accounts/templates/signup.htm
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
{% extends "base.html" %}
{% block content %}
    <title></title>
  </head>
  <body>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
<input type="submit" value="Signup">
  </body>
{% endblock %}
</html>

accounts/templates/signup.html
{% load static %}

    <title>SIGNUP</title>
  </head>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
  <link rel="stylesheet" href="{% static 'css/all.css' %}">
  <body style="background-image: url('{% static "images/back4.jpg" %}') ;100%";>
    <style>
    #middle {
      position: relative;
      padding : 10Px;
      top : 30%;
      left : 18%;
    }
  .button {
  display: inline-block;
  border-radius: 2px;
  background-color: #052ee2;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 18px;
  padding: 10px;
  width: 100px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 3px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
    </style>
    
<a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>
<div id='middle' style="border-radius: 25px ;border:3px solid gray; position: relative;top:2%; width:58%;height:65%;">
 
<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<input type="submit" value="Signup">
</form>
<hr>
<h3> Already a member? <a href="{% url 'accounts:login' %}"><button class='button'><span>Login</span> </button> </a></h3>
</div>

<div style="border: thin 2px; bottom:-30px; position: relative; ">
    <div align="center" id="footer"> 
        <a href="{% url 'aboutus' %}">About Us</a>
        <a href="{% url 'privacy' %}">Privacy Policy</a>
        
        <a href="{% url 'faq' %}">FAQ</a>
      
    </div>
<footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
</div>

  </body>

blog/templates/about_us.html
{% load static %}
<head><link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
        <script>
                $('body').highlight("{{query_string}}");
            </script>
        
        <a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>
        {% if user.is_authenticated %}
                     <li><form class="logout-link" action="/accounts/logout/" method="POST">
                       {% csrf_token %}
                     <button style='float:right' type="submit">Logout</button>
                     </li>
                     <button>
                     <a href="/blog/create">New Article</a>
                     </button>   
        {% else %}
        <div align='right'>
          <button>
          <a href="/accounts/login">Login</a>
          </button>
          <button>
          <a href="/accounts/signup">Signup</a>
        </button>
        </div>
        
        {% endif %}
        
          {% block content %}
          {% endblock %}
          <hr>
    <title>About Us</title>
        {% load static %}
    </head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    body{
        background-color: azure;
    }
    .team img{
        border-radius: 50%; 
        border: 6px double;


    }
    .team{
        display: inline-flex;
        border: 3px solid transparent;
        width: 100%;
        height: 100%;
    }
    .sameer, .bibek{
        position: relative;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        color: aqua;
        border: 3px solid;
        width: 45%;
        height: 70%;
        margin: 3%;
        padding: 3%;
    }
    .fa{
    padding: 8px;
    font-size: 20px;
    text-align: center;
    border: 3px solid goldenrod;
    border-radius: 50%;
    color: white;
    width: 20px;
}
#social_links{
    border: 3px;
    
   top:30px;
    position: relative;
    
}
.fa-facebook{
    background: #3B5998;
}
.fa-twitter{
    background:  #55ACEE;
}
.fa-instagram{
    background: #b25c4a;
;
}
.fa-github{
    background: #3B5998;
}
.fa-linkedin{
    background: #007bb5;
}
   
    </style>
    <body>
        <h1 style="text-align: center">Our Team</h1>
        <span class="team">
        <div class="sameer">
                <img src="{% static "images/sameer.jpg" %}" alt="Sameer Lamsal" height="260px" width="260px" />
                <h3>Sameer Lamsal</h3>
                <hr>
                <p style="color: black">
                        Hi! I am Samir Lamsal, Currently studying bachelor of electronics, communication and information technology.
                </p>
                <span id="social_links">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-github"></a>
                    <a href="#" class="fa fa-instagram"></a>
            </span>
            </div>
                <div class="Bibek">
                <img src="{% static "images/myy.jpg" %}" alt="Bibek Chalise" height="260px" width="260px" />
                <h3>
                    Bibek Chalise
                </h3>  
                <hr> 
                <p style="color: black">
                        Hi! I am Bibek Chalise, currently studying bachelor of Computer Engineering.
                    </p>
                    <span id="social_links">
                        <a href="https://www.facebook.com/IamBbek" class="fa fa-facebook"></a>
                        <a href="https://twitter.com/I_am_Bbek" class="fa fa-twitter"></a>
                        <a href="https://www.linkedin.com/in/bibek-chalise-235380142/" class="fa fa-linkedin"></a>
                        <a href="https://github.com/bibekebib" class="fa fa-github"></a>
                        <a href="https://www.instagram.com/im_bbek/" class="fa fa-instagram"></a>
                </span>
        </div>
    </span>
    <div align="center" id="footer"> 
            <a href="{% url 'aboutus' %}">About Us</a>
            <a href="{% url 'privacy' %}">Privacy Policy</a>
            
            <a href="{% url 'faq' %}">FAQ</a>
          
        </div>
    <footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
    </body>

blog/templates/add_article.html
{% load static %}

<a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>
<hr>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head><link rel="stylesheet" href="{% static 'css/all.css' %}">
    <meta charset="utf-8">
    <title>Add-Article</title>
  </head>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
  <style>
  #middle{
    position: relative;
    top:10%;
    left:25%;
    padding: 10px;
    border-radius:15px; border: 2px solid gray; width:40%; position: relative;

  }
  </style>
  <body style="background-image: url('{% static "images/back4.jpg" %}');height:600px;">
      <h1>Add an awesome article here</h1>
      <hr size="2", color="brown">
    <div id="middle">
        
        <form class="site-form" action="/blog/create" method="post">
          {% csrf_token %}
          {{ form.as_p }}
        <input type="submit" value="Create">
        </form>
    </div>
    <div style="border: thin 2px; bottom:-100px; position: relative; ">
        <div align="center" id="footer"> 
            <a href="{% url 'aboutus' %}">About Us</a>
            <a href="{% url 'privacy' %}">Privacy Policy</a>
            
            <a href="{% url 'faq' %}">FAQ</a>
          
        </div>
    <footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
  </body>
</html>

blog/templates/authors.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% block content %}
  <head>
    <meta charset="utf-8">
    <title>Authors</title>


  </head>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
  <body>
    <h1>Hall Of Fame</h1>
    {% for writers in writers %}
    <a href="{{ writers.id }}">{{ writers.name }}<a/><br>
    {% endfor %}

  </body>
  <div>
    {% for author in author %}
    <a href="{{ author.id }}">
        {{ author.author }}<br><br>
    </a>
    {% endfor %}
  </div>
<footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>
  {% endblock %}

</html>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head><link rel="stylesheet" href="{% static 'css/all.css' %}">
    <meta charset="utf-8">
    <title></title>
    <script>
        $('body').highlight("{{query_string}}");
    </script>

<a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>
{% if user.is_authenticated %}
             <li><form class="logout-link" action="/accounts/logout/" method="POST">
               {% csrf_token %}
             <button style='float:right' type="submit">Logout</button>
             </li>
             <button>
             <a href="/blog/create">New Article</a>
             </button>
{% else %}
<div align='right'>
  <button>
  <a href="/accounts/login">Login</a>
  </button>
  <button>
  <a href="/accounts/signup">Signup</a>
</button>
</div>

{% endif %}
<div align="center" id="footer">
    <a href="{% url 'aboutus' %}">About Us</a>
    <a href="{% url 'privacy' %}">Privacy Policy</a>

    <a href="{% url 'faq' %}">FAQ</a>

</div>

  {% block content %}
  {% endblock %}
  </head>
  <body >

  </body>
</html>

blog/templates/faq.html
{% load static %}
<head>
                <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
        <link rel="stylesheet" href="{% static 'css/all.css' %}">
</head>
<div align="center" id="footer"> 
        <a href="{% url 'aboutus' %}">About Us</a>
        <a href="{% url 'privacy' %}">Privacy Policy</a>
        
        <a href="{% url 'faq' %}">FAQ</a>
      
    </div>
<footer style="font-size: 28px; color:red; text-align: center">An ICES Project!</footer>

blog/templates/home.html
{% load static %}
<html>
    <head><link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
            <link rel="stylesheet" href="{% static 'css/all.css' %}">
    </head>
        <title>Welcome to DotBlog!</title>

    </head>
    <body style="background-image   : url('{% static "images/baak.png" %}');height:500px; background-size:contain;";>
<style>
h1 a{
  opacity: 0.8;
}
</style>
            <h1>
              <a href="/blog/"><img src="{% static 'images/titlelogo.gif' %}"/></a>

                <div  align="center" style="width:100%;height:20%;color:royalblue;position:absolute;top:10%;border:3px solid transparent">
                               Welcome to DotBlog!<br>
                        An online Blogging Platform! <br>
                        <a href="/blog/">Take a Tour</a>
                </div>
            </h1>
        <div style="border:3px solid transparent; position:absolute;top:34%;width:100%;height:47%;">
                   <div id="signup"><a href="{% url 'accounts:signup'%}">Sign Up!</a></div>
                   <div id="login"><a href="{% url 'accounts:login' %}">Login</a></div>
                </div>
        <div style="border:3px solid transparent; position:absolute;top:85%;width:100%;height:5%">
            <div align="center" id="footer">
                <a href="{% url 'aboutus' %}">About Us</a>
                <a href="{% url 'privacy' %}">Privacy Policy</a>

                <a href="{% url 'faq' %}">FAQ</a>

            </div>
        </div>

    </body>

</html>

blog/templates/homepage.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

{% block content %}
  <head>
    <meta charset="utf-8">
    <title>Blogs</title>
  </head>

  <style>
   #middle{
    position: relative;
    left:10%;
    padding: 10px;
    border-radius:15px; border: 2px solid gray; width:40%; position: relative;

  }
  </style>
  <body style="background-image: url('{% static "images/back4.jpg" %}');height:600px;";>
    <b>

      <div align="center">Welcome!</div></b><hr/><br/>
    <h1>
            Login to add a new Blog    </h1><br/><br/>
   <div id ="middle">
     <h2>Take a look at our authors</h2>
     <a href="/authors/">Authors</a>
   </div>
    <div id="middle">
     <h2>Recent Blogs</h2><br><br>
      <div>
          {% for articles in articles %}
          <a href="{{ articles.id }}">
              {{ articles.title }}   <pre>-{{ articles.author }}</pre><br><br>
          </a>
          {% endfor %}

      <a href="/authors/"

      {% endblock %}
      </div>


    </div>
  </body>

</html>

blog/templates/search.html
<html>
    <title>Search</title>
    <body>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <form id="searchform" action="{{% request.get_host %}}/blog,search/" method="GET">
            <input type="text" name="q" id="text"/>
            <button type="button" onclick="searchform.submit()">
            search
            </button>
        </form>
    </body>
</html>

blog/templates/writers.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% extends "base.html" %}
{% block content %}
{% load static %}

  <head>
    <meta charset="utf-8">
    <title>{{ lekhak.name }}</title>

  </head>
  <body>
  <hr/>
    {{ lekhak.image }}<br/>
    <hr/>
  Author---->  {{ lekhak.name }}<br/>
  Bio----->    {{ lekhak.Bio }}<br/>
  Articles------>  {{ lekhak.articles }}<br/>

  </body>
{% endblock %}

</html>

blog/templates/writings.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% extends "base.html" %}
{% block content %}
  <head>
    <title>Articles</title>
    <meta charset="utf-8">
    <title>{{ material.title }}</title>
  </head>
  <body>
    <div>
      <h1>Running successfully</h1></br>
      <h2>{{material.title}}</h2></br></br></br>
      <hr/></br>


        {{material.body}}</br>
        Written by: {{ material.author }}</br>


        </div>
  </body>
{% endblock %}
</html>